version: '3.3'

services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.11
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 9080:80
    depends_on:
      - postgres
